### ISSUE TITLE
Medaljelele would like to get generator for summaries of guild posts

### ISSUE THREAD

**Issue by IndigoWilke** [Dsek-LTH/web#324] opened 2024-05-06 20:15 UTC
As above. Every year the committee hands out medals depending on come criteria. The old website had a system of generating a list with the people who were entitled to medals and since loosing that functionality, the awarding of medals has become harder and people who deserved medals have been missed on ceremonies. This is not time critical but it would be nice to have it implemented during the fall. The ceremony is held in February so most of the information would concern the last calendar year. I list the criteria for medals below.

Styrelsemedaljer: Heads of committees (for the new year)
Funktionärsmedalj: People who completed their first post, 
Gammal && Äcklig: People who have had ANY post for the last four years (or three whereof one in the guilds board)
Utskottsmedaljer: People who have served in the same committee for three years (and which)

**Comment by danieladugyan** [comment] 2024-06-24 22:50
Closing as duplicate of #125

**Closed by danieladugyan** 2024-06-24 22:50 UTC
Labels: enhancement
